### ISSUE TITLE
Implement minimum and maximum timespans to protect against DoS

### ISSUE THREAD

**Issue by svierne** [anoadragon453/matrix-reminder-bot#128]
### Observed behaviour
With the current implementation, the bot can be DoSed by setting up a recurring reminder as follows:
`!remindroom every 1 second; now; spam`

### Proposed fix
Implement config variables for minimum and maximum timespans, e.g.

```yaml
reminders:
    timespan_min: "1 minute"
    timespan_max: "1 year"
```

For reminders above and below the timespan limit, the bot should respond with an error.
