### ISSUE TITLE
Bot is not joining any room

### ISSUE THREAD

**Issue by Dzordzu** [anoadragon453/matrix-reminder-bot#62]
## Current behaviour
Bot does nor react on any message nor invite. 

## Expected behaviour
Bot doest accept request

## Logs and config
Includes manual restarts

<details>
<summary> Docker logs </summary>

```
reminder-bot_1      | 2020-11-17 15:33:56,745 | matrix_reminder_bot.storage [INFO] Performing initial database setup...
reminder-bot_1      | 2020-11-17 15:33:56,809 | matrix_reminder_bot.storage [INFO] Migrating the database from v0 to v1...
reminder-bot_1      | 2020-11-17 15:33:56,878 | matrix_reminder_bot.storage [INFO] Database migrated to v1
reminder-bot_1      | 2020-11-17 15:33:56,878 | matrix_reminder_bot.storage [INFO] Migrating the database from v1 to v2...
reminder-bot_1      | 2020-11-17 15:33:56,887 | matrix_reminder_bot.storage [INFO] Database migrated to v2
reminder-bot_1      | 2020-11-17 15:33:56,887 | matrix_reminder_bot.storage [INFO] Migrating the database from v2 to v3...
reminder-bot_1      | 2020-11-17 15:33:56,892 | matrix_reminder_bot.storage [INFO] Database migrated to v3
reminder-bot_1      | 2020-11-17 15:33:56,893 | matrix_reminder_bot.storage [INFO] Database initialization of type 'postgres' complete
reminder-bot_1      | 2020-11-17 15:33:57,738 | matrix_reminder_bot.main [INFO] Logged in as @reminderbot:matirx.dzordzu.pl
reminder-bot_1      | 2020-11-17 15:33:57,738 | matrix_reminder_bot.main [INFO] Startup complete
reminder-bot_1      | 2020-11-17 15:33:57,741 | apscheduler.scheduler [INFO] Scheduler started
reminder-bot_1      | 2020-11-17 15:36:03,703 | matrix_reminder_bot.storage [DEBUG] Loaded reminder rows: []
reminder-bot_1      | 2020-11-17 15:36:03,704 | matrix_reminder_bot.storage [INFO] Database initialization of type 'postgres' complete
reminder-bot_1      | 2020-11-17 15:36:04,325 | matrix_reminder_bot.main [INFO] Logged in as @reminderbot:matirx.dzordzu.pl
reminder-bot_1      | 2020-11-17 15:36:04,326 | matrix_reminder_bot.main [INFO] Startup complete
reminder-bot_1      | 2020-11-17 15:36:04,328 | apscheduler.scheduler [INFO] Scheduler started
reminder-bot_1      | 2020-11-17 15:36:04,330 | apscheduler.scheduler [DEBUG] Looking for jobs to run
reminder-bot_1      | 2020-11-17 15:36:04,331 | apscheduler.scheduler [DEBUG] No jobs; waiting until a job is added
reminder-bot_1      | 2020-11-17 15:43:35,904 | matrix_reminder_bot.storage [DEBUG] Loaded reminder rows: []
reminder-bot_1      | 2020-11-17 15:43:35,905 | matrix_reminder_bot.storage [INFO] Database initialization of type 'postgres' complete
reminder-bot_1      | 2020-11-17 15:43:36,059 | matrix_reminder_bot.main [ERROR] Failed to login: Unrecognized request
reminder-bot_1      | 2020-11-17 15:43:36,060 | matrix_reminder_bot.main [WARNING] Trying again in 15s...
reminder-bot_1      | 2020-11-17 15:43:51,127 | matrix_reminder_bot.main [ERROR] Failed to login: Unrecognized request
reminder-bot_1      | 2020-11-17 15:43:51,128 | matrix_reminder_bot.main [WARNING] Trying again in 15s...
reminder-bot_1      | 2020-11-17 15:44:11,257 | matrix_reminder_bot.storage [DEBUG] Loaded reminder rows: []
reminder-bot_1      | 2020-11-17 15:44:11,258 | matrix_reminder_bot.storage [INFO] Database initialization of type 'postgres' complete
reminder-bot_1      | 2020-11-17 15:44:11,838 | matrix_reminder_bot.main [INFO] Logged in as @reminderbot:matirx.dzordzu.pl
reminder-bot_1      | 2020-11-17 15:44:11,839 | matrix_reminder_bot.main [INFO] Startup complete
reminder-bot_1      | 2020-11-17 15:44:11,841 | apscheduler.scheduler [INFO] Scheduler started
reminder-bot_1      | 2020-11-17 15:44:11,844 | apscheduler.scheduler [DEBUG] Looking for jobs to run
reminder-bot_1      | 2020-11-17 15:44:11,845 | apscheduler.scheduler [DEBUG] No jobs; waiting until a job is added
```

</details>

<details>
<summary> Config </summary>

```
command_prefix: "!"

matrix:
  user_id: "@reminderbot:matirx.dzordzu.pl"
  user_password: *******
  homeserver_url: https://matrix.dzordzu.pl
  device_id: "REMINDERBOT_1"
  device_name: "Reminder Bot"

storage:
  database: "postgres://matrix:******@postgres/reminderbot"

reminders:
  # timezone: "Europe/London"

logging:
  level: DEBUG
  file_logging:
    enabled: true
    filepath: /data/bot.log
  console_logging:
    enabled: true
```

</details>
